### ISSUE TITLE
Allow for concept overlap

### ISSUE THREAD

**Issue by bramiozo** [umcu/clinlp#78]
Maybe possible to allow for concept overlap? Ostensibly it is just the following

In ```clinlp.entity``` 

```{python}
class EntityMatcher:
  def __init__(... , allow_overlap: Optional[bool] = _defaults_clinlp_ner["overlap"])
          self.term_args = {... "overlap": allow_overlap}
  ...
  
  def __call__()
          if self.term_args['overlap']==False:
            ents = self._resolve_ents_overlap(ents)
```

**Comment by bramiozo** [comment]
@vmenger, deze tackle ik tegelijk met dit/deze issue: https://github.com/umcu/clinlp/issues/67

**Comment by vmenger** [comment]
@bramiozo That line `_resolve_ents_overlap` is there by the way to make sure spaCy does not raise any errors when overlap occurs, because entities are not allowed to overlap in spaCy. If we want overlap (I think we maybe do), we would need to start using spans rather than entities. We can also work together on it if you like

See also: #65 and #36
